import {
  signUp,
  signUpPost,
  verifyEmail,
  verifyEmailPost,
  forgetPassword,
  forgetPasswordPost,
  resetPassword,
  resetPasswordPost,
  login,
  loginPost,
} from './authController.js';
import {
  userIndex,
  uploadUserImage,
  request,
  requestPost,
  allRequest,
  wastage,
  allWastage,
  wastagePost,
  profile,
  profilePost,
} from './userController.js';

import {
  adminIndex,
  uploadAdminImage,
  allUser,
  addUser,
  addUserPost,
  updateAccountStatus,
  viewUser,
  editUser,
  editUserPost,
  deleteUser,
  allProduct,
  addProduct,
  addProductPost,
  editProduct,
  editProductPost,
  deleteProduct,
  allWastages,
  adminProfile,
  requestProduct,
} from './adminController.js';

export {
  //auth
  signUp,
  signUpPost,
  verifyEmail,
  verifyEmailPost,
  forgetPassword,
  forgetPasswordPost,
  resetPassword,
  resetPasswordPost,
  login,
  loginPost,
  //user
  userIndex,
  uploadUserImage,
  request,
  requestPost,
  allRequest,
  wastage,
  allWastage,
  wastagePost,
  profile,
  profilePost,
  //admin
  adminIndex,
  uploadAdminImage,
  allUser,
  addUser,
  addUserPost,
  updateAccountStatus,
  viewUser,
  editUser,
  editUserPost,
  deleteUser,
  allProduct,
  addProduct,
  addProductPost,
  editProduct,
  editProductPost,
  deleteProduct,
  allWastages,
  requestProduct,
  adminProfile,
};
