import { log } from './logger.js';
import { sendMail } from './mail.js';
import { generateUniqueRef } from './otpUtils.js';
import { sanitizeInput, sanitizeObject } from './inputSanitizer.js';
import {
  paginatedResults,
  userRequestFilter,
  rejectedRequestFilter,
  acceptRequestFilter,
  pendingRequestFilter,
  acceptReturnFilter,
  rejectedReturnFilter,
  pendingReturnFilter,
  pendingWasteFilter,
  acceptWasteFilter,
  rejectedWasteFilter,
} from './pagination.js';
import {
  welcomeEmail,
  awaitingVerifyEmail,
  approveEmail,
  forgetPasswordEmail,
  resetPasswordEmail,
  loginEmail,
  accountStatusMail,
  requestProductMail,
  returnProductMail,
  wasteProductMail,
  updateProfile,
  requestUpdateMail,
  returnUpdateMail,
  wasteUpdateMail,
} from './emailTemplates.js';

import {
  getAvailableMaterials,
  getRequestedMaterials,
  getWastedMaterials,
  getReturnedMaterials,
} from './materialCount.js';

export {
  log,
  sendMail,
  generateUniqueRef,
  welcomeEmail,
  approveEmail,
  awaitingVerifyEmail,
  forgetPasswordEmail,
  resetPasswordEmail,
  loginEmail,
  accountStatusMail,
  requestProductMail,
  returnProductMail,
  wasteProductMail,
  updateProfile,
  returnUpdateMail,
  requestUpdateMail,
  wasteUpdateMail,
  sanitizeInput,
  sanitizeObject,
  paginatedResults,
  userRequestFilter,
  rejectedRequestFilter,
  acceptRequestFilter,
  pendingRequestFilter,
  acceptReturnFilter,
  rejectedReturnFilter,
  pendingReturnFilter,
  pendingWasteFilter,
  acceptWasteFilter,
  rejectedWasteFilter,
  getAvailableMaterials,
  getRequestedMaterials,
  getWastedMaterials,
  getReturnedMaterials,
};
